## Bài 1. Tạo Tensor cơ bản

Tạo một Tensor số nguyên kích thước 2 × 3 và hiển thị kết quả.

**Yêu cầu:** Cho biết kích thước, số chiều và kiểu dữ liệu của Tensor a.

In [1]:
import torch
a = torch.tensor(
[[1, 2, 3],
[4, 5, 6]],
dtype=torch.int32
)
print(a)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


## Bài 2. Tạo các Tensor thường dùng
Thực hành tạo Tensor ngẫu nhiên, Tensor toàn số 0, toàn số 1 và ma trận đơn vị.

**Yêu cầu:**  
• Nhận xét sự khác nhau giữa torch.rand() và torch.randn().  
• Tạo thêm một Tensor 5 × 5 chứa toàn giá trị 10.

In [2]:
import torch
a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)
print(a)
print(b)
print(c)
print(d)
print(e)

tensor([[0.3751, 0.3832, 0.2864, 0.9910],
        [0.1263, 0.3260, 0.8722, 0.7361],
        [0.4361, 0.3174, 0.8627, 0.1890]])
tensor([[-0.3120,  1.0136,  0.2861,  1.1788],
        [ 1.7310, -0.6372, -1.1948, -1.0855],
        [-0.0063, -1.3595, -0.6292,  0.3875]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [3]:
# Tạo thêm một Tensor 5 × 5 chứa toàn giá trị 10.
f = torch.full((5, 5), 10)
print(f)

tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])


## Bài 3. Kiểm tra thông tin Tensor
Sử dụng shape, size(), ndim và dtype để kiểm tra các thuộc tính của Tensor.

**Yêu cầu:** Giải thích ý nghĩa của torch.Size([2, 3, 4]).

In [4]:
import torch
a = torch.zeros(2, 3, 4)
print("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


## Bài 4. Slicing và Indexing
Truy xuất một phần dữ liệu từ Tensor nhiều chiều.

**Yêu cầu:**  
• Cho biết shape của a[1] và a[1:, 2:4].  
• Thử lấy hai phần tử cuối cùng trên chiều thứ ba.

In [5]:
import torch
a = torch.randn(3, 4, 5)
print("Original tensor:")
print(a)
print("\nTensor a[1]:")
print(a[1])
print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])

Original tensor:
tensor([[[-0.0435, -2.9035,  1.1672,  1.8154, -0.5726],
         [-1.4956, -0.1726,  1.4098, -0.6468, -1.5355],
         [-0.4192,  0.5290,  0.3970, -0.8715, -1.7948],
         [-1.4926, -1.1869,  0.2031, -0.5026,  0.1047]],

        [[-1.4530,  1.2869, -0.1385, -0.4295,  1.2404],
         [ 0.8090,  0.0435, -0.6550,  0.7031, -0.5676],
         [-0.9211, -0.9922,  1.7980, -1.5906,  0.9233],
         [ 1.0200,  0.6164, -0.4540, -0.4473,  0.7480]],

        [[ 0.0600,  0.2520,  0.2371, -0.3665, -0.3438],
         [ 1.0663, -1.0458, -0.2934, -1.3522, -1.6901],
         [-1.0839,  1.1061, -0.2461, -0.0260, -0.5235],
         [-0.6614, -2.0756,  0.2741,  0.0274,  1.5897]]])

Tensor a[1]:
tensor([[-1.4530,  1.2869, -0.1385, -0.4295,  1.2404],
        [ 0.8090,  0.0435, -0.6550,  0.7031, -0.5676],
        [-0.9211, -0.9922,  1.7980, -1.5906,  0.9233],
        [ 1.0200,  0.6164, -0.4540, -0.4473,  0.7480]])

Tensor a[1:, 2:4]:
tensor([[[-0.9211, -0.9922,  1.7980, -1.5906,  0.9

In [6]:
# lấy hai phần tử cuối cùng trên chiều thứ ba.
print(a[:, :, -2:])

tensor([[[ 1.8154, -0.5726],
         [-0.6468, -1.5355],
         [-0.8715, -1.7948],
         [-0.5026,  0.1047]],

        [[-0.4295,  1.2404],
         [ 0.7031, -0.5676],
         [-1.5906,  0.9233],
         [-0.4473,  0.7480]],

        [[-0.3665, -0.3438],
         [-1.3522, -1.6901],
         [-0.0260, -0.5235],
         [ 0.0274,  1.5897]]])


## Bài 5. Reshape và Flatten
Thay đổi hình dạng Tensor mà không làm thay đổi số phần tử.

**Yêu cầu:**  
• Kiểm tra số phần tử trước và sau khi reshape.  
• Thử reshape Tensor thành kích thước 2 × 6.

In [7]:
import torch
a = torch.randn(3, 4)
print("Original:")
print(a)
print("\nFlatten:")
print(a.ravel())
print("\nReshape to 3 x 2 x 2:")
print(a.reshape(3, 2, 2))

Original:
tensor([[-1.3134,  1.7450, -0.1885, -0.6686],
        [ 1.9121, -0.1690,  1.0017, -1.5013],
        [-1.6606, -0.7865,  1.1334, -2.1490]])

Flatten:
tensor([-1.3134,  1.7450, -0.1885, -0.6686,  1.9121, -0.1690,  1.0017, -1.5013,
        -1.6606, -0.7865,  1.1334, -2.1490])

Reshape to 3 x 2 x 2:
tensor([[[-1.3134,  1.7450],
         [-0.1885, -0.6686]],

        [[ 1.9121, -0.1690],
         [ 1.0017, -1.5013]],

        [[-1.6606, -0.7865],
         [ 1.1334, -2.1490]]])


In [8]:
# reshape Tensor thành kích thước 2 x 6:
print(a.reshape(2, 6))

tensor([[-1.3134,  1.7450, -0.1885, -0.6686,  1.9121, -0.1690],
        [ 1.0017, -1.5013, -1.6606, -0.7865,  1.1334, -2.1490]])


## Bài 6. Phép toán và nhân ma trận
Thực hiện các phép toán phần tử và phép nhân ma trận bằng toán tử @.

**Yêu cầu:**  
• Phân biệt phép toán a * b với a @ b.T.  
• Cho biết shape của kết quả a @ b.T.

In [9]:
import torch
a = torch.randn(2, 3)
b = torch.randn(2, 3)
print("a:")
print(a)
print("b:")
print(b)
print("\na + b:")
print(a + b)
print("\na / b:")
print(a / b)
print("\na^2:")
print(a ** 2)
print("\nMatrix multiplication:")
print(a @ b.T)

a:
tensor([[-1.8839,  1.2159,  0.4894],
        [-0.0551,  0.9978,  0.7162]])
b:
tensor([[ 1.6533, -0.4705, -0.8648],
        [ 1.1499,  1.0164, -0.4187]])

a + b:
tensor([[-0.2306,  0.7454, -0.3755],
        [ 1.0948,  2.0141,  0.2974]])

a / b:
tensor([[-1.1395, -2.5843, -0.5658],
        [-0.0479,  0.9817, -1.7103]])

a^2:
tensor([[3.5492e+00, 1.4783e+00, 2.3947e-01],
        [3.0396e-03, 9.9554e-01, 5.1291e-01]])

Matrix multiplication:
tensor([[-4.1100, -1.1356],
        [-1.1800,  0.6508]])


## Bài 7. Các hàm thống kê trên Tensor
Tính trung bình, độ lệch chuẩn và tổng tích lũy theo từng cột.

**Yêu cầu:**  
• Thay dim=0 bằng dim=1 và nhận xét sự khác nhau.

In [10]:
import torch
a = torch.randn(3, 4)
print(a)
print("\nMean:")
print(torch.mean(a, dim=0))
print("\nStandard deviation:")
print(torch.std(a, dim=0))
print("\nCumulative sum:")
print(torch.cumsum(a, dim=0))

tensor([[ 0.2652, -1.7136, -0.7615, -0.9958],
        [ 1.2235,  0.0464,  1.2434, -0.8803],
        [ 0.0603,  0.5552, -0.5149,  0.1496]])

Mean:
tensor([ 0.5163, -0.3706, -0.0110, -0.5755])

Standard deviation:
tensor([0.6209, 1.1905, 1.0933, 0.6306])

Cumulative sum:
tensor([[ 0.2652, -1.7136, -0.7615, -0.9958],
        [ 1.4887, -1.6671,  0.4819, -1.8761],
        [ 1.5489, -1.1119, -0.0331, -1.7265]])


In [11]:
import torch
a = torch.randn(3, 4)
print(a)
print("\nMean:")
print(torch.mean(a, dim=1))
print("\nStandard deviation:")
print(torch.std(a, dim=1))
print("\nCumulative sum:")
print(torch.cumsum(a, dim=1))

tensor([[ 2.6719,  0.1185,  0.3655, -1.8862],
        [ 0.5577,  0.4665,  0.0595,  0.5981],
        [ 1.1727,  0.3757,  0.7647,  0.1165]])

Mean:
tensor([0.3175, 0.4205, 0.6074])

Standard deviation:
tensor([1.8656, 0.2469, 0.4615])

Cumulative sum:
tensor([[2.6719, 2.7904, 3.1560, 1.2698],
        [0.5577, 1.0242, 1.0837, 1.6818],
        [1.1727, 1.5484, 2.3131, 2.4296]])


## Bài 8. Autograd cơ bản
Tạo biến có requires_grad=True và dùng backward() để tính đạo hàm tự động.

**Yêu cầu:**  
• Tính thủ công đạo hàm của y = x2 tại x = 3.6 và so sánh với x.grad.  
• Đổi hàm thành y = 3*x\*\*2 + 2\*x + 1 và kiểm tra gradient.

In [12]:
import torch
x = torch.tensor(
3.6,
requires_grad=True
)
y = x * x
y.backward()
print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(12.9600, grad_fn=<MulBackward0>)
x.grad = tensor(7.2000)


In [13]:
# Đổi hàm thành y = 3x2 + 2x + 1 và kiểm tra gradient:n
x = torch.tensor(3.6, requires_grad=True)
y = 3 * x**2 + 2 * x + 1
y.backward()
print("x.grad =", x.grad)

x.grad = tensor(23.6000)


## Bài 9. Gradient Descent tìm hệ số đa thức
Sinh dữ liệu từ đa thức y = x2 + 2x + 3, sau đó dùng NAdam và autograd để tìm lại ba hệ số.

**Yêu cầu:**  
• So sánh ba hệ số học được với [1, 2, 3].  
• Giải thích vai trò của optimizer.zero_grad(), mse.backward() và optimizer.step().

In [14]:
import numpy as np
import torch

polynomial = np.poly1d([1, 2, 3])
N = 20
X = np.random.randn(N, 1) * 5
Y = polynomial(X)

XX = np.hstack([
    X * X,
    X,
    np.ones_like(X)
])

w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)
optimizer = torch.optim.NAdam([w], lr=0.01)

print("Initial coefficients:")
print(w)

for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()

print("Learned coefficients:")
print(w)

Initial coefficients:
tensor([[ 0.3356],
        [-0.3005],
        [ 0.8738]], requires_grad=True)
Learned coefficients:
tensor([[1.0036],
        [1.9934],
        [2.7305]], requires_grad=True)


## Bài 10. Giải hệ phương trình bằng Autograd
Tối thiểu hóa tổng sai số bình phương để tìm A, B, C, D thỏa bốn phương trình.

**Yêu cầu:**  
• Kiểm tra nghiệm thu được với bốn phương trình: A+B=9, C-D=1, A+C=8, B-D=2.  
• Nhận xét vì sao bài toán có thể có nhiều nghiệm.

In [15]:
import random
import torch
A = torch.tensor(random.random(), requires_grad=True)
B = torch.tensor(random.random(), requires_grad=True)
C = torch.tensor(random.random(), requires_grad=True)
D = torch.tensor(random.random(), requires_grad=True)
EPOCHS = 2000
optimizer = torch.optim.NAdam([A, B, C, D], lr=0.01)
for _ in range(EPOCHS):
    y1 = A + B - 9
    y2 = C - D - 1
    y3 = A + C - 8
    y4 = B - D - 2
    sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4
    optimizer.zero_grad()
    sqerr.backward()
    optimizer.step()
print("A =", A)
print("B =", B)
print("C =", C)
print("D =", D)

A = tensor(4.2504, requires_grad=True)
B = tensor(4.7495, requires_grad=True)
C = tensor(3.7495, requires_grad=True)
D = tensor(2.7495, requires_grad=True)


## Bài 11. Viết chương trình PyTorch để thực hiện các yêu cầu sau:

• Tạo Tensor X có 24 phần tử và reshape lần lượt thành 4 × 6, 2 × 12 và 2 × 3 × 4.  
• Tạo hai Tensor A, B kích thước 3 × 4; tính A+B, A*B, A/B, trung bình theo cột và độ lệch chuẩn theo cột.  
• Cho y = 2x2 + 5x + 3. Dùng autograd tính dy/dx tại x = 2 và kiểm tra bằng phép tính thủ công.  
• Thay đa thức trong Bài 9 bằng y = 2x2 - 3x + 5; huấn luyện và cho biết các hệ số tìm được.

In [16]:
import torch
# Tạo Tensor 24 phần tử
X = torch.arange(24)
# Reshape lần lượt
X_4x6 = X.reshape(4, 6)
X_2x12 = X.reshape(2, 12)
X_2x3x4 = X.reshape(2, 3, 4)

print("Shape 4x6:\n", X_4x6.shape)
print("Shape 2x12:\n", X_2x12.shape)
print("Shape 2x3x4:\n", X_2x3x4.shape)

Shape 4x6:
 torch.Size([4, 6])
Shape 2x12:
 torch.Size([2, 12])
Shape 2x3x4:
 torch.Size([2, 3, 4])


In [17]:
# Tạo Tensor A và B ngẫu nhiên kích thước 3x4
A = torch.rand(3, 4)
B = torch.rand(3, 4)

print("A + B:\n", A + B)
print("A * B:\n", A * B)
print("A / B:\n", A / B)
# Tính trung bình và độ lệch chuẩn theo cột (dim=0)
print("Trung bình theo cột của A:\n", torch.mean(A, dim=0))
print("Độ lệch chuẩn theo cột của A:\n", torch.std(A, dim=0))

A + B:
 tensor([[1.5178, 0.4485, 0.5100, 1.0452],
        [0.8983, 1.5226, 0.6073, 1.3152],
        [1.5311, 0.2350, 1.0271, 0.7198]])
A * B:
 tensor([[0.5283, 0.0013, 0.0533, 0.1803],
        [0.1535, 0.5788, 0.0221, 0.3777],
        [0.5546, 0.0090, 0.2513, 0.0959]])
A / B:
 tensor([[1.8071, 0.0063, 2.4795, 3.7953],
        [0.3434, 1.0745, 0.0685, 2.1037],
        [1.6037, 0.2560, 1.5545, 0.3251]])
Trung bình theo cột của A:
 tensor([0.7166, 0.2798, 0.3425, 0.6317])
Độ lệch chuẩn theo cột của A:
 tensor([0.4221, 0.4413, 0.2936, 0.3955])


In [18]:
# Tính bằng Autograd
x = torch.tensor(2.0, requires_grad=True)
y = 2 * x**2 + 5 * x + 3
y.backward()

print("Đạo hàm tính bằng Autograd tại x=2:", x.grad.item())

Đạo hàm tính bằng Autograd tại x=2: 13.0


In [19]:
import numpy as np
# Tạo đa thức y = 2x^2 - 3x + 5
polynomial = np.poly1d([2, -3, 5])
N = 20
X_data = np.random.randn(N, 1) * 5
Y_data = polynomial(X_data)
# Ghép khối tạo dữ liệu đầu vào
XX = np.hstack([X_data * X_data, X_data, np.ones_like(X_data)])

w = torch.randn(3, 1, requires_grad=True)
x_tensor = torch.tensor(XX, dtype=torch.float32)
y_tensor = torch.tensor(Y_data, dtype=torch.float32)
optimizer = torch.optim.NAdam([w], lr=0.01)
# Quá trình huấn luyện
for epoch in range(2000):
    optimizer.zero_grad()
    y_pred = x_tensor @ w
    mse = torch.mean(torch.square(y_tensor - y_pred))
    mse.backward()
    optimizer.step()

print("Hệ số tìm được:\n", w)

Hệ số tìm được:
 tensor([[ 2.0206],
        [-2.9318],
        [ 3.8239]], requires_grad=True)
